### ISSUE TITLE
mac用户无权限

### ISSUE THREAD

**Issue by xiaoxian521** [Yikun/hub-mirror-action#128]
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
是不是考虑判断使用环境，mac需要加sudo

**Comment by xiaoxian521** [comment]
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
是不是考虑判断使用环境，mac需要加sudo

**Comment by Yikun** [comment]
@xiaoxian521 本地跑？还是github action的mac资源？

**Comment by xiaoxian521** [comment]
> @xiaoxian521 本地跑？还是github action的mac资源？

action

**Comment by xiaoxian521** [comment]
配置文件
https://github.com/xiaoxian521/pure-admin-backend/blob/main/.github/workflows/gitee-repos-mirror.yml

**Comment by xiaoxian521** [comment]
![image](https://user-images.githubusercontent.com/44761321/144955545-bbb9ecaf-4d35-400b-b63c-6154e015b984.png)

**Comment by Yikun** [comment]
https://github.com/pure-admin-backend 没有这个组织

看配置：
https://github.com/xiaoxian521/pure-admin-backend/blob/8064c3fe7cee0aa05ca4727241b3b75ca217c010/.github/workflows/gitee-repos-mirror.yml#L16

也是跑在ubuntu上的，所以，问题应该是仓库配错了？

**Comment by xiaoxian521** [comment]
你可以看下这个action的报错信息
https://github.com/xiaoxian521/pure-admin-backend/runs/4438662281?check_suite_focus=true#step:3:14
key和token我按照文档都配置过了😂

**Comment by Yikun** [comment]
哦，同步xiaoxian521账号下的`pure-admin-backend`仓库？那应该这么写：
```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/xiaoxian521
          dst: gitee/xiaoxian521
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          timeout: 600
          force_update: true
          white_list: pure-admin-backend
```
