### ISSUE TITLE
能不能在GitHubr的仓库A中执行Actions，把仓库B同步到Gitee？

### ISSUE THREAD

**Issue by Kukmoon** [Yikun/hub-mirror-action#149]
我用GitHub写博客，博客源文件在仓库A，图床在仓库B。现在我有一个需求：就是只要向仓库A推送新的内容，就在仓库A中执行Actions，把仓库B中的内容同步到Gitee的同名仓库。请问 `hub-mirror-action` 可以满足我这个需求吗？应该怎么操作呀？

**Comment by yi-Xu-0100** [comment]
可以的，你看使用案例就知道，他只是同步两个仓库，并没有说要在对应仓库下执行。

**Comment by Yikun** [comment]
嗯，在A仓库加个B仓库同步的workflow就可以。

```
- name: Mirror B
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/yourgithubid
    dst: gitee/yourgiteeid
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    static_list: "B"
```
