### ISSUE TITLE
AttributeError: 'Hub' object has no attribute 'src_repo_base'

### ISSUE THREAD

**Issue by zerofo** [Yikun/hub-mirror-action#170]
Traceback (most recent call last):
  File "/hub-mirror/hubmirror.py", line 102, in <module>
    mirror.run()
  File "/hub-mirror/hubmirror.py", line 53, in run
    hub = Hub(
  File "/hub-mirror/hub.py", line 36, in __init__
    self.src_repo_base = self.src_repo_base + self.src_account
AttributeError: 'Hub' object has no attribute 'src_repo_base'

**Comment by Yikun** [comment]
@zerofo 对应的yaml或者调用命令贴下？

**Comment by zerofo** [comment]
```
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: zerofo/t9xz
          dst: zerofo/t9xz
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
```
@Yikun

**Comment by Yikun** [comment]
```
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/zerofo
          dst: gitee/zerofo
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
```

Try this @zerofo, hub mirror是整个账户或者组织的同步。如果你想同步指定的仓库:

```
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/zerofo
          dst: gitee/zerofo
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "t9xz"
```
