### ISSUE TITLE
同步非private，但是fork的仓库同步如何做？

### ISSUE THREAD

**Issue by SWHL** [Yikun/hub-mirror-action#175]
- 目前一直在用`hub-mirror-action`，很好用，我看README中只写了如何**仅同步非private，非fork的仓库**
- 最近想着备份**同步非private，但是fork的仓库**到gitee，但是找了一圈，实在没找到配置选项
- 希望大佬可以指点一二，感谢❀

**Comment by SWHL** [comment]
感谢，收到，通过查看[repo-list-generator文档](https://github.com/yi-Xu-0100/repo-list-generator)已经解决
解决方案是，详情参见：[RapidAI actions](https://github.com/RapidAI/.github/blob/main/.github/workflows/SyncToGitee.yml)
```yml
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
    src: 'github/RapidAI'
    dst: 'gitee/RapidAI'
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token:  ${{ secrets.GITEE_TOKEN }}
    force_update: true
    account_type: org
    debug: true
    static_list: ${{ steps.repo.outputs.repoList_FORK }}  # 仅同步非private的仓库，包括fork和自建的
```
