### ISSUE TITLE
应该如何避免总任务超时

### ISSUE THREAD

**Issue by EzrealJ** [Yikun/hub-mirror-action#176]
### 如题

执行的环节出现了一些问题，原因不明，但总的任务卡住直到达到github action时间上限。
The job running on runner GitHub Actions 2 has exceeded the maximum execution time of 360 minutes.

引用action
https://github.com/WebApiClient/WebApiClientWiki/actions/runs/4876538051
workflow如下

```yml
name: Sync Github Repos To Gitee
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Organization mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/webapiclient
          dst: gitee/webapiclient
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
```

我并未配置任何超时参数。
