### ISSUE TITLE
同步gitee 失败

### ISSUE THREAD

**Issue by mxcad** [Yikun/hub-mirror-action#178]
报错：
```sh
Cmd('git') failed due to: exit code(1)
cmdline: git push gitee refs/remotes/origin/*:refs/heads/* --tags --prune
stderr: 'To gitee.com:mxcadx/mxdraw_docs.git
! [rejected]        origin/gh-pages -> gh-pages (fetch first)
```

**Comment by Yikun** [comment]
@mxcad 应该是gitee侧包含有github未包含的commits引起的。

```yaml
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/mxcad'
          dst: 'gitee/mxcadx'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "mxdraw_docs"
          force_update: true
```

加下force_update试下
https://github.com/Yikun/hub-mirror-action#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0
