### ISSUE TITLE
github action处理python包PyYAML报错

### ISSUE THREAD

**Issue by rainoffallingstar** [Yikun/hub-mirror-action#181]
`+ pip3 install -r /hub-mirror/requirements.txt
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting PyYAML==5.4.1

  Downloading PyYAML-5.4.1.tar.gz (175 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 4.1 MB/s eta 0:00:00

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error`

**Comment by Yikun** [comment]
```
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@v1.3
  with:
```

```
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
```

使用v1.3后版本，或者master版本
