### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by toFrankie** [Yikun/hub-mirror-action#188]
「Github 同步到 Gitee」

两端的私钥、密钥、Token 那些都正确配置了，尝试过重新生成，也不行。搜索过一些相关的 Issue（比如 [#108](https://github.com/Yikun/hub-mirror-action/issues/108)）看起来配置都没问题

其中 `id_rsa` 配置到 github 里的 Actions secrets and variables，也就是 `GITEE_PRIVATE_KEY`，其中 `id_rsa.pub` 也配置到 Gitee 里了。`GITEE_TOKEN` 也配置了，就是不成功。

@Yikun 大佬 help~

- [Workflow](https://github.com/toFrankie/blog/blob/2c173b8de73c78e3fdd05ba2eaec4860363d454f/.github/workflows/sync-to-gitee.yml)
- [Action Log](https://github.com/toFrankie/blog/actions/runs/8314658546)

```yml
name: Sync to Gitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/toFrankie
          dst: gitee/frankie_li
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'blog'
          account_type: user
          force_update: true
          debug: true
```

主要报错如下：

```
Cmd('git') failed due to: exit code(128)
  cmdline: git push -f gitee refs/remotes/origin/*:refs/heads/* --tags --prune
  stderr: 'git@gitee.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

![](https://github.com/Yikun/hub-mirror-action/assets/26947203/86d85496-0e05-4f49-aa14-5cd0103a4bee)

配置没错：

<img width="906" alt="image" src="https://github.com/Yikun/hub-mirror-action/assets/26947203/f25754aa-c1a2-4fca-8e99-d15d3011def3">

<img width="1090" alt="image" src="https://github.com/Yikun/hub-mirror-action/assets/26947203/7ab60fb6-1c67-4486-945e-8871c6466a29">

<img width="1055" alt="image" src="https://github.com/Yikun/hub-mirror-action/assets/26947203/cfc05b6e-7707-4be3-b871-e332ffcc32a0">
