### ISSUE TITLE
feat: add option to support git push with -f

### ISSUE THREAD

**Issue by Ir1d** [Yikun/hub-mirror-action#27]
It is useful for gh-pages branch, because it is a generated orphan branch in every update.

**Comment by Yikun** [comment]
@Ir1d thanks for you feedback, and I will add this feature soon (maybe in this week).

and looks like we could add a `force_update` input arg, and default is `false`, and if user want to push with -f flag, he can use something as below:

```yaml
- name: Mirror with force push (git push -f)
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/Yikun
    dst: gitee/yikunkero
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    force_update: true
```
