### ISSUE TITLE
可以支持同步多分支吗？

### ISSUE THREAD

**Issue by jardenliu** [Yikun/hub-mirror-action#35]
当前好像只会同步master

**Comment by Yikun** [comment]
默认就支持的

**Comment by jardenliu** [comment]
emmmm, 难道是我打开方式不对。。设置了static_list会有影响吗？

**Comment by Yikun** [comment]
`static_list`只是少了动态获取repo列表的操作，不会影响的。

有Link吗，我看看

**Comment by jardenliu** [comment]
action文件：https://github.com/jardenliu/XPS15-9560-Catalina/blob/master/.github/workflows/sync-gitee.yml

从 https://github.com/jardenliu/XPS15-9560-Catalina 同步到 https://gitee.com/yeliujun/XPS15-9560-Catalina. 
辛苦看下

**Comment by Yikun** [comment]
@jardenliu 看着脚本本身没什么问题，分支同步应该也是可以的。

所以看看是不是因为没触发？参考下官方的[触发配置]：(https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)

```
# Trigger the workflow on push or pull request
on: [push, pull_request]
```
或者，类似这种：
```
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - master
      # Push events to branches matching refs/heads/mona/octocat
      - 'mona/octocat'
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
```

不知道是不是branches: [x, y, z]这种不支持？
