### ISSUE TITLE
能否提供设置以便不同步 fork 的仓库

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#42]
其实我只是想将我的个人创建的仓库同步过去，但是 fork 的仓库太多了，自己创建的也挺多的。

能不能直接设置参数，不同步 fork 的仓库，这样我的名单能够短点，只需要排除1-2个私有仓库。

对喽，如果这样可行的话，自行创建的私有仓库的，希望能够判断出来后直接跳过，给出 warning 即可，最好在文档中说明暂时无法同步。（#38 的问题就可以暂时避免）

**Comment by Yikun** [comment]
@yi-Xu-0100 不同步某种仓库的需求还是建议使用黑/白名单参数实现。不同步fork这种有点太特殊，通用性差一些，所以，个人觉得优先级偏低。

**Comment by yi-Xu-0100** [comment]
考虑到经常 fork 仓库收藏，可能对我这样的 fork 的仓库很多的人说，黑白名单需要设置的太多了……

个人会一直期待后面的更新~😊

**Comment by ouuan** [comment]
> 不同步某种仓库的需求还是建议使用黑/白名单参数实现。不同步fork这种有点太特殊，通用性差一些

优先级低可以理解，但是不同步 fork 这个需求真的很难用黒白名单实现

**Comment by yi-Xu-0100** [comment]
@ouuan 可以参考 #49 中我给出的解决方案。

**Comment by yi-Xu-0100** [comment]
@Yikun 

```yaml
outputs:
  repoList:
    description: >
      Repository list exclude private and fork.
      Public(source without private) and no fork.
  forkList:
    description: >
      Fork repository list.
      Only fork(private can not be fork).
```

可以看到，如果 private repo 也在同步列表内，可能会造成同步失败(当前好像还不支持？)。所以我一般是使用的默认提供的 repoList

```yaml
### 仅同步非fork并且非private的仓库
- name: get non-fork/private list
  id: repo
  uses: yi-Xu-0100/repo-list-generator@v1.0.1
- name: static list
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/Yikun
    dst: gitee/yikunkero
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    static_list: ${{ steps.repo.outputs.repoList }}
```
