### ISSUE TITLE
支持同步仓库名映射（例如从xxx.github.io同步至xxx）

### ISSUE THREAD

**Issue by 21ki** [Yikun/hub-mirror-action#45]
示例为https://github.com/21ki/21ki.github.io  同步到https://gitee.com/myki/myki.gitee.io
因为gitee不支持数字开头的仓库所以到gitee的时候修改了个名字，造成同步不成功，这个有解吗？

**Comment by Yikun** [comment]
@21ki 目前能力是不支持从一个A名字的库，同步到B名字的库。

**Comment by yi-Xu-0100** [comment]
@21ki 你可以先使用 gitee 同步仓库的方式，创建这个仓库，然后这个 action 的推送应该是没有问题的。

见 [yi-Xu-0100/hub-mirror#gitee-无法创建-xxx-仓库如何解决](https://github.com/yi-Xu-0100/hub-mirror#gitee-%E6%97%A0%E6%B3%95%E5%88%9B%E5%BB%BA-xxx-%E4%BB%93%E5%BA%93%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

**Comment by Yikun** [comment]
> 你可以先使用 gitee 同步仓库的方式，创建这个仓库

@yi-Xu-0100 没理解这个过程，这个过程还是会限制不让用特殊字符吧？

**Comment by yi-Xu-0100** [comment]
@Yikun 是的，数字开头的仓库可以通过 github 导入的方式创建，这样无需修改仓库名，可以绕过无法创建仓库的问题。
特殊字符的话，则只能重命名仓库等其他方式了。一般很少由特殊字符开头的，但是数字开头的有可能。

**Comment by yi-Xu-0100** [comment]
@21ki 那没救了，我会更新文档，我以为官方帮助手册说的可以……不知道是不是最近改了

**Comment by Yikun** [comment]
所以，结论应该是由于Gitee的限制，无法做到同步。另外，对于这种不同repo名字的同步，应该支持吗？如果想支持的话有什么优雅的办法吗？

我个人认为不应该支持，：），因为破坏了Hub同步的概念，不应该对某个库有特殊的处理。

但话说回来，这种由于各Hub见的能力不同，导致的差异，应该有些机制可以弥补，如果让我做的话，我可能会通过一个配置设置一些mapping规则：

```
steps:
- name: Mirror the Github organization repos to Gitee with mapping.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/21ki
    dst: gitee/Myki
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    mapping: "21ki.github.io=Myki"
```

这是一个比较理想的实现吗?

**Comment by 21ki** [comment]
这样刚觉还不错哦

**Comment by Yikun** [comment]
想了下，这个需求有一定的用户场景，例如进行blog page同步的时候。

github默认的page服务在repo：xxx.github.io
而gitee默认的page服务在repo：xxx

所以有那种从xxx.github.io到xxx的需求，类似这种：
```
steps:
- name: Mirror the Github organization repos to Gitee with mapping.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/xxx
    dst: gitee/xxx
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    mapping: "xxx.github.io=xxx"
```

所以，这个需求会实现的，我再想下这个mapping的规则，看如何更通用一些。

**Comment by fakedon** [comment]
我想了种方式，提供fmt，类似python中logger的formatter，经过`sed -r $fmt`处理得到dst_repo

例如
```
steps:
- name: Mirror the Github organization repos to Gitee with mapping.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/user
    dst: gitee/user
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    mapping: fmt='s/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g
    static_list: 'repo'
```
目的仓库名输出为github_user_repo

例如
```
steps:
- name: Mirror the Github organization repos to Gitee with mapping.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/user
    dst: gitee/user
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    mapping: fmt='s/(.*).github.io/\1/g
    static_list: 'xxx.github.io'
```
目的仓库名输出为xxx

不擅长bash，东拼西凑瞎写了下 lol
代码行链接：https://github.com/fakedon/hub-mirror/blob/regex/entrypoint.sh#L240
