### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lxk0301** [Yikun/hub-mirror-action#46]
看这个示例文件修改的
https://github.com/Yikun/hub-mirror-action/blob/master/.github/workflows/verify-on-ubuntu-org.yml

修改使用后的文件 https://github.com/lxk0301/scripts/blob/master/.github/workflows/SyncToGitee.yml
错误截图
![image](https://user-images.githubusercontent.com/21308593/95535215-7eefbc00-0a1a-11eb-89bc-3f1b7fe057d2.png)

错误action地址 https://github.com/lxk0301/scripts/runs/1229263924?check_suite_focus=true

**Comment by Yikun** [comment]
@lxk0301 action名字错了吧？

https://github.com/lxk0301/scripts/commit/ac06991257886f94211ce10a438dd8d06e3b0381#diff-02d9c370a663741451423342d5869b21

```
- name: Normal user mirror
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/kunpengcompute
    dst: gitee/kunpengcompute
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
```

**Comment by Yikun** [comment]
应该是受到https://github.com/Yikun/yikun.github.com/issues/79 的误导，这个是当时最初版本，我把文章也同步更新了下。

**Comment by lxk0301** [comment]
你好， 这种可行吗？
```
name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,10,16,22 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Normal user mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/kunpengcompute
          dst: gitee/kunpengcompute
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
```

**Comment by Yikun** [comment]
@lxk0301 底下配置没问题，上面action配置触发条件你确认好应该就OK

**Comment by lxk0301** [comment]
> @lxk0301 底下配置没问题，上面action配置触发条件你确认好应该就OK

好的， 这种配置应该是同步github账号里面的所有项目到 gitee吧，  没有单个的吗？

**Comment by Yikun** [comment]
@lxk0301 可以，使用static_list参数，比如
```
static_list: repo1
```
仅同步repo1这个仓库

**Comment by lxk0301** [comment]
还是会报错， 我的 gitee 的SSH公钥是 ssh-rsa开头的，应该没有错误吧
action运行日志
action 配置如下

```
name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,10,16,22 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Normal user mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lxk0301
          dst: gitee/lxk0301
          static_list: scripts
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
```

https://github.com/lxk0301/scripts/runs/1230611486?check_suite_focus=true
![image](https://user-images.githubusercontent.com/21308593/95568519-ecb9d900-0a56-11eb-93f3-67bce9c60068.png)

![image](https://user-images.githubusercontent.com/21308593/95566429-1d4c4380-0a54-11eb-8932-0cdb0c0f94c4.png)
