### ISSUE TITLE
Gitee如何同步到GitHub

### ISSUE THREAD

**Issue by YouthLin** [Yikun/hub-mirror-action#63]
GitHub 可以用 Actions，但是 Gitee 好像没有这个功能呀，只有 WebHook

**Comment by Yikun** [comment]
@YouthLin 可以用Github Action周期任务，然后进行同步。

```
name: Gitee repos mirror periodic job

on:
  schedule:
    # Runs at 0,2,4,6...,22th hour every day (every 2 hours)
    - cron:  '0 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the gitee repos to github.
      uses: Yikun/hub-mirror-action@master
      with:
        src: gitee/xxxx
        dst: github/xxx
        dst_key: ${{ secrets.SYNC_MINDSPORE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_MINDSPORE_TOKEN }}
```
