### ISSUE TITLE
能否支持设置只同步某些分支

### ISSUE THREAD

**Issue by lencx** [Yikun/hub-mirror-action#79]
例如：
```yml
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
    # ...
    # 默认同步所有分支，如果设置branches，则同步以逗号分割的分支
    branches: 'a,b'
```

**Comment by yi-Xu-0100** [comment]
因为是同步多个仓库，如果只同步某些分支，很难对单个仓库去指定。

建议直接单仓库设置定时脚本，推送部分分支到远程库

**Comment by lencx** [comment]
我认为这个扩展性的问题吧，如果该`action`只用于同步多个仓库，不细化，也是ok的。但是如果放在场景中，需求是千奇百怪的，每次去写脚本，也是复杂的。可以对单个仓库实现一些自定义不知道是否算一定的通用性？

**Comment by Yikun** [comment]
@lencx 能了解下仅同步某个分支具体的原始诉求是啥样的吗？

**Comment by lencx** [comment]
也可能只是我个人的需求，想把build后的文件目录推送到gitee上做一个镜像部署，并不希望将源码也同步到gitee。
`peaceiris/actions-gh-pages`是支持自动构建推送，但不支持推送gitee。而`Yikun/hub-mirror-action`支持的应该是多仓库定时同步。当时提issues的时候，是我没搞清楚该项目的定位，抱歉。

**Comment by Yikun** [comment]
@lencx : )，存在即合理哈。你现在用其他工具可以实现了吗？单个仓库指定分支同步的可以参考类似[1]中的action。

另外，对于批量的branch这个需求，可能在未来也会考虑，优先级很低。

[1] https://github.com/marketplace?type=actions&query=mirror

**Comment by lencx** [comment]
我目前暂未折腾了。谢谢你的参考[1]，有时间再学习一下。

**Comment by Ir1d** [comment]
我提一个场景， gitee 好像对 gh-pages 不会 gc，总是莫名其妙报错，所以会有只同步 master 分支的需求

**Comment by HalfSweet** [comment]
目前我们可以尝试增加一个`branch_mappings`的字段用于同步某些分支和进行映射，例如：
```yaml
with:
  branch_mappings: |
    - repo: A
      branches:
        - src: main
          dst: master
        - src: dev
          dst: dev1
        - pattern: release/*
    - repo: B
      branches:
        - src: main
          dst: master
        - src: dev
          dst: dev1
        - pattern: release/*
```
其中，`pattern`用于指示不需要映射的情况，源分支和目标分支名称均一致，并且支持使用`*`的通配符
