### ISSUE TITLE
Add acoount type support

### ISSUE THREAD

**Issue by Yikun** [Yikun/hub-mirror-action#8]
Current, only org account type repo sync is supported, but the user account type is not suported.

We can ~~add an `is_org` (False by default)~~add a `account_type` (can be set to `user` or `org`, `user` by default) to get/list the repos from user account or org account.  

The org sync：
```yaml
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/kunpengcompute
    dst: gitee/kunpengcompute
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token:  ${{ secrets.GITEE_TOKEN }}
    account_type: org
```

The user sync：
```yaml
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/xxx
    dst: gitee/xxx
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token:  ${{ secrets.GITEE_TOKEN }}
```
